// defines.h

#ifndef __DEFINES_H__
#define __DEFINES_H__

#define SETBIT(WORD, BITPOS) (WORD |= 1<<BITPOS)
#define SSETBIT(WORD, BITPOS) (WORD = 1<<BITPOS)
#define CLRBIT(WORD, BITPOS) (WORD &= (~(1<<BITPOS)))
#define SCLRBIT(WORD, BITPOS) SSETBIT(WORD, BITPOS)
#define CPLBIT(WORD, BITPOS) (WORD, BITPOS) (WORD ^= 1<<BITPOS)
#define READBIT(WORD, BITPOS) ((WORD>>BITPOS)&1)

#define WRITEBYTE(WORD, SBITPOS, BYTE) (WORD = (WORD &~(255<<SBITPOS))| (VALUE<<SBITPOS))
#define WRITEBYTE(WORD, SBITPOS, NIBBLE) (WORD = (WORD &~(15<<SBITPOS))| (NIBBLE<<SBITPOS))
#define WRITEBYTE(WORD, SBITPOS, BIT) = ((WORD &~(1<<SBITPOS))| (BIT<<SBITPOS))
